services:
  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata: